# Generated by Django 4.0.1 on 2023-08-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
